# =============================================================================
# Bloat específico de Fedora (un paquete por línea)
# =============================================================================

mediawriter
gnome-boxes
