# =============================================================================
# Bloat del escritorio KDE Plasma (un paquete por línea)
# =============================================================================

kontact
akregator
kmail
kaddressbook
korganizer
dragonplayer
kmahjongg
kreversi
kpat
kmines
ksudoku
elisa
konversation
kleopatra
krdc
krfb
