# =============================================================================
# Listas de software para Debian / Ubuntu / Mint ... (gestor: apt)
# Formato:  categoria: paquete1 paquete2 ...
# Edita libremente para adaptarlas a tus necesidades.
# =============================================================================

esenciales: git curl wget htop tmux vim tree unzip ripgrep fd-find fzf jq fastfetch file timeshift flatpak kdeconnect
multimedia: ffmpeg ffmpegthumbnailer vlc mpv obs-studio handbrake
desarrollo: gcc g++ make cmake git-lfs python3 python3-pip nodejs npm docker docker-compose neovim flatpak:com.vscodium.codium
internet: firefox chromium flatpak:io.github.zen_browser.zen flatpak:com.bitwarden.desktop
oficina: libreoffice thunderbird evolution gnucash pandoc texlive-base flatpak:org.onlyoffice.desktopeditors
juegos: steam lutris gamemode mangohud flatpak:com.heroicgameslauncher.hgl flatpak:com.usebottles.bottles
gnome-utiles: gnome-tweaks gnome-shell-extensions dconf-editor gnome-shell-extension-manager gnome-shell-extension-gsconnect
terminal: zsh alacritty kitty
utilidades: stacer
descargas: transmission

# --- perfiles profesionales ------------------------------------------------
informatica: nmap netcat-openbsd wireshark tcpdump iperf3 mtr traceroute dnsutils whois net-tools openssl btop ncdu duf bat eza p7zip-full unzip rsync sshfs tmux screen chkrootkit rkhunter fail2ban gparted hwinfo smartmontools ethtool
dev-plus: podman buildah skopeo golang-go cargo rustc openjdk-17-jdk python3-venv python3-pipx postgresql postgresql-contrib mariadb-server redis-server sqlite3 gitg meld nginx
contenido: kdenlive shotcut openshot blender audacity yt-dlp
diseno-grafico: gimp inkscape krita darktable rawtherapee digikam shotwell imagemagick pinta mypaint gcolor3
