# =============================================================================
# Listas de software para Arch / Manjaro / EndeavourOS ... (gestor: pacman)
# Formato:  categoria: paquete1 paquete2 ...
# Edita libremente para adaptarlas a tus necesidades.
# =============================================================================

esenciales: git curl wget htop tmux vim tree unzip ripgrep fd fzf jq fastfetch file timeshift flatpak kdeconnect
multimedia: ffmpeg ffmpegthumbnailer vlc mpv obs-studio handbrake
desarrollo: gcc make cmake git-lfs python python-pip nodejs npm docker docker-compose neovim flatpak:com.vscodium.codium
internet: firefox chromium flatpak:io.github.zen_browser.zen flatpak:com.bitwarden.desktop
oficina: libreoffice-fresh thunderbird evolution gnucash pandoc texlive-core flatpak:org.onlyoffice.desktopeditors
juegos: steam lutris gamemode mangohud flatpak:com.heroicgameslauncher.hgl flatpak:com.usebottles.bottles
gnome-utiles: gnome-tweaks gnome-extensions-app dconf-editor gnome-shell-extension-appindicator gnome-shell-extension-dash-to-dock gnome-shell-extension-blur-my-shell gnome-extension-manager gnome-shell-extension-gsconnect
terminal: zsh alacritty kitty
utilidades: stacer
descargas: transmission-gtk

# --- perfiles profesionales ------------------------------------------------
informatica: nmap gnu-netcat wireshark-cli tcpdump iperf3 mtr traceroute bind-tools whois net-tools openssl btop ncdu duf bat eza p7zip unzip rsync sshfs tmux screen chkrootkit rkhunter fail2ban gparted hwinfo smartmontools ethtool
dev-plus: podman buildah skopeo go rust jdk-openjdk python-virtualenv python-pipx postgresql mariadb redis sqlite gitg meld nginx
contenido: kdenlive shotcut openshot blender audacity yt-dlp
diseno-grafico: gimp inkscape krita darktable rawtherapee digikam shotwell imagemagick pinta mypaint gcolor3
